Update zh_cn
object-Object/hexbound pull request #2
Opened 2024-07-16 19:01 UTC by ChuijkYahus

2024-08-31 18:19 UTC, object-Object requested changes
Thanks for the update! I'm sorry for the delay, I didn't see this at the time because I forgot to enable notifications for this repo. It seems like a couple of the book links are broken.

2024-08-31 18:19 UTC, object-Object commented on src/main/resources/assets/hexbound/lang/zh_cn.flatten.json5
> +                      最终找到了$(l:hexcasting:greatwork/spellcircle)某些独立于施法者的施法方式$()（或者改装一下发射器让它能甩动缀品说不定也行），\
I think this is supposed to be `hexcasting:greatwork/spellcircles`.

2024-08-31 18:19 UTC, object-Object commented on src/main/resources/assets/hexbound/lang/zh_cn.flatten.json5
> +            "1": "如今我已有控制意识的能力，我又读了一遍有关$(l:hexbound:patterns/great_spells/impetus_fake_player)绑定虚意识$()的笔记，并确认了$(l:hexcasting:greatwork/impetuses)牧师促动石$()是虚意识的极佳容器。\
I think this is supposed to be `hexcasting:greatwork/impetus`.

2024-09-01 04:15 UTC, ChuijkYahus commented
Sorry for the broken links, fixed now.

2024-09-01 04:59 UTC, object-Object approved these changes
thanks!

2024-09-01 05:03 UTC, merged